- name: Launching argocd declaratively
  hosts: servers
  become: true
  vars: 
    pathLune: /home/lune

  tasks:
    - name: Let's copy the required file
      ansible.builtin.copy:
        src: ../../../kubernetes/application.yaml
        dest: "{{ pathLune }}/application.yaml"

    - name: Apply application.yaml 
      ansible.builtin.shell: |
        kubectl apply -n argocd -f "{{ pathLune }}/application.yaml"

    - name: Delete the obsolete file
      ansible.builtin.file:
        path: "{{ pathLune }}/application.yaml"
        state: absent
